version: '3'

services:
  master:
    image: locustio/locust
    container_name: locust-master
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://host.docker.internal:3000
    environment:
      - LOCUST_MODE=master

  worker:
    image: locustio/locust
    container_name: locust-worker
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
    environment:
      - LOCUST_MODE=worker
